commit_message: '[ci skip]'
files:
  - source: /app/lib/l10n/app_en.arb
    translation: /app/lib/l10n/app_%osx_locale%.arb
  - source: /docs/content/translations/en.json
    translation: /app/lib/l10n/%two_letters_code%.json
  - source: /docs/content/docs/docs/**/*
    translation: /docs/content/docs/%two_letters_code%/docs/**/%original_file_name%
